#pragma once
#include "Error.h"
#include "Parm.h"
#include "In.h"
#include "Log.h"
#include "Out.h"
#include "FST.h"
#include "Graphs.h"
#include "IT.h"
#include "LexAnalysis.h"
#include "LT.h"
#include "GRB.h"
#include "MFST.h"
#include "PolishNotation.h"
#include <iostream>
#include <fstream>
#include <Windows.h>
#include <tchar.h>
#include <stack>
#include <queue>
#include <iomanip>
